title: Vu Trung Nguyen (Bob)
logo: C:\Users\PC\vutrung.github.io\assets\img\My_Portrait_circle.png
# description: "I'm a software engineer, a blogger, and a lifelong learner. I'm passionate about software engineering, web development, and data science. I love to share my knowledge and experience with the community."
# show_downloads: true
theme: jekyll-theme-minimaL