title: Vu Trung Nguyen (Bob)
# logo: /assets/images/logo.png
# description: "I'm a software engineer, a blogger, and a lifelong learner. I'm passionate about software engineering, web development, and data science. I love to share my knowledge and experience with the community."
# show_downloads: true
theme: jekyll-theme-minimal